### ISSUE TITLE
Issue with language switching

### ISSUE THREAD

**Issue by iamdarkle** [android-com-pl/flarum-lscache#1]
I have detected that using the extension the language selector (when installing an additional language pack) stops working, so you cannot change the language of the page and you cannot use it to change the language of FoF Discussion Language, although I think it is not a problem of the latter because you can change the language of the discussions from the integrated selector of FoF Discussion Language.

**Comment by rafaucau** [comment]
Thanks for reporting. I had forgotten this option existed.

@iamdarkle Can you check if it works for you?

You can replace this line in .htaccess
```apache
RewriteRule .* - [E="Cache-Vary:flarum_remember,flarum_lscache_vary"]
```
to this one:
```apache
RewriteRule .* - [E="Cache-Vary:flarum_remember,flarum_lscache_vary,locale"]
```

Then purge all LSCache

**Comment by iamdarkle** [comment]
Yes, thank you very much, it works perfectly.
